### ISSUE TITLE
Variant read incorrectly

### ISSUE THREAD

**Issue by collin-beard** [roxitsc/InstaExtension#11]
On http://www.localsolar.ca/ (Page ID 867731) the variant get stuck at Q although you are circling trough them using /?variant=

Video: http://take.ms/95zpK

**Comment by roxitsc** [comment]
Fix update. This can be tested on http://forexttest.instapage.com/?variant=A (it's a duplicate). current variants active: A, K, T for testing.

After fix is accepted, please unpublish and remove duplicate page from roxi account.

**Comment by collin-beard** [comment]
Tested it and works OK. I unpublished and deleted the page, Case closed.
