### ISSUE TITLE
Publish the extension on Chrome WebStore

### ISSUE THREAD

**Issue by calinbrb** [roxitsc/InstaExtension#7]
Research how to publish this for easier use and updating by our agents.

**Comment by roxitsc** [comment]
Where you submit the plugin - https://chrome.google.com/webstore/developer/dashboard
Before submitting the extension we need to make sure we go through: https://developer.chrome.com/extensions
https://developer.chrome.com/webstore
https://developer.chrome.com/extensions/manifest/icons

We might need bigger icons etc.

**Comment by roxitsc** [comment]
We can publish it when I get online tomorrow, if you don't have time to check those links and double check the extension we can still publish it like it is.

**Comment by roxitsc** [comment]
Make sure to create relase in git - https://github.com/roxitsc/InstaExtension/releases
